apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.cluster-jlxsx.jlxsx.sandbox3230.opentlc.com/rhtap/test:b397aab447ecc5558f138921c73758f0f0d189d8@sha256:e59223a95ef58fac9d5d4443e0141788244d7fadf44bc44e493ae0cfd97c94a6
          name: container-image
